// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public interface RunGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunGraphResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<org.tensorflow.framework.NamedTensorProto> 
      getRecvList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProto getRecv(int index);
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  int getRecvCount();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getRecvOrBuilderList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProtoOrBuilder getRecvOrBuilder(
      int index);

  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  boolean hasStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStats getStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder();

  /**
   * <code>optional .tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  boolean hasCostGraph();
  /**
   * <code>optional .tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  org.tensorflow.framework.CostGraphDef getCostGraph();
  /**
   * <code>optional .tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  org.tensorflow.framework.CostGraphDefOrBuilder getCostGraphOrBuilder();

  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<org.tensorflow.framework.GraphDef> 
      getPartitionGraphList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDef getPartitionGraph(int index);
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  int getPartitionGraphCount();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<? extends org.tensorflow.framework.GraphDefOrBuilder> 
      getPartitionGraphOrBuilderList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDefOrBuilder getPartitionGraphOrBuilder(
      int index);
}
